
CELL_SIZE = 30      
GRID_WIDTH = 15  
GRID_HEIGHT = 15 

START_SNAKE_POSITION = (GRID_WIDTH// 2, GRID_HEIGHT//2)
WINDOW_WIDTH = CELL_SIZE * GRID_WIDTH
WINDOW_HEIGHT = CELL_SIZE * GRID_HEIGHT


FPS = 60              
  


BACKGROUND_COLOR = (50, 115, 168)
GRID_COLOR = (0,0,0)   
SNAKE_COLOR = (54, 168, 50)    
      

START_LENGTH = 3
START_POS = (GRID_WIDTH // 2, GRID_HEIGHT // 2) 